from __future__ import annotations

import os
import sys
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from dotenv import load_dotenv
from psycopg import Connection, connect
from psycopg.errors import Error as PsycopgError


class DatabaseConfigurationError(RuntimeError):
    """Raised when database configuration is missing or unusable."""


@dataclass(frozen=True)
class SchemaInitializationResult:
    tables_created: tuple[str, ...]
    hypertable_created: bool
    hypertable_message: str


BACKEND_DIR = Path(__file__).resolve().parent
ENV_FILE = BACKEND_DIR / ".env"


def load_database_url() -> str:
    load_dotenv(ENV_FILE)
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise DatabaseConfigurationError(
            "DATABASE_URL is required for Tiger Data persistence."
        )
    return database_url


@contextmanager
def get_connection() -> Iterator[Connection]:
    try:
        connection = connect(load_database_url())
    except DatabaseConfigurationError:
        raise
    except PsycopgError as exc:
        raise DatabaseConfigurationError("Unable to connect to Tiger Data.") from exc

    try:
        yield connection
    finally:
        connection.close()


def initialize_schema() -> SchemaInitializationResult:
    """Create RxSignal persistence tables without dropping existing data."""

    hypertable_created = False
    hypertable_message = "Timescale/Tiger hypertable creation was not attempted."

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS label_snapshots (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    drug_key TEXT NOT NULL,
                    generic_name JSONB NOT NULL DEFAULT '[]'::jsonb,
                    brand_name JSONB NOT NULL DEFAULT '[]'::jsonb,
                    manufacturer JSONB NOT NULL DEFAULT '[]'::jsonb,
                    indications_and_usage JSONB NOT NULL DEFAULT '[]'::jsonb,
                    warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
                    boxed_warning JSONB NOT NULL DEFAULT '[]'::jsonb,
                    contraindications JSONB NOT NULL DEFAULT '[]'::jsonb,
                    adverse_reactions JSONB NOT NULL DEFAULT '[]'::jsonb,
                    effective_time TEXT,
                    source JSONB NOT NULL DEFAULT '{}'::jsonb,
                    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    PRIMARY KEY (id, captured_at)
                )
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_label_snapshots_drug_time
                ON label_snapshots (drug_key, captured_at DESC)
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS detected_signals (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    drug_key TEXT NOT NULL,
                    previous_snapshot_id BIGINT,
                    current_snapshot_id BIGINT,
                    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    changed_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
                    changes JSONB NOT NULL DEFAULT '[]'::jsonb,
                    priority_score INTEGER NOT NULL,
                    priority_level TEXT NOT NULL,
                    priority_reasons JSONB NOT NULL DEFAULT '[]'::jsonb
                )
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_detected_signals_drug_time
                ON detected_signals (drug_key, detected_at DESC)
                """
            )

        connection.commit()

        try:
            with connection.cursor() as cursor:
                cursor.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
                cursor.execute(
                    """
                    SELECT create_hypertable(
                        'label_snapshots',
                        'captured_at',
                        if_not_exists => TRUE,
                        migrate_data => TRUE
                    )
                    """
                )
            hypertable_created = True
            hypertable_message = (
                "label_snapshots is configured as a Timescale/Tiger hypertable."
            )
        except PsycopgError as exc:
            connection.rollback()
            hypertable_message = (
                "Timescale/Tiger hypertable setup was unavailable; "
                "ordinary PostgreSQL tables remain usable."
            )
            # Avoid logging exception details because provider errors can include
            # connection or role metadata that is not useful in API responses.
            _ = exc

        else:
            connection.commit()

    return SchemaInitializationResult(
        tables_created=("label_snapshots", "detected_signals"),
        hypertable_created=hypertable_created,
        hypertable_message=hypertable_message,
    )


if __name__ == "__main__":
    try:
        result = initialize_schema()
    except DatabaseConfigurationError as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(1) from None

    print("RxSignal database schema initialized.")
    print(f"Tables: {', '.join(result.tables_created)}")
    print(result.hypertable_message)
