import { Sparkles, FilePenLine, ShieldCheck, Users, Info } from "lucide-react";
import type { MedicationAlert } from "@/types/medication";

type Brief = MedicationAlert["intelligenceBrief"];
type Props =
  | { loading: true; brief?: never }
  | { loading?: false; brief: Brief };

const sections = [
  { key: "whatChanged", title: "What changed", icon: FilePenLine },
  { key: "whyItMatters", title: "Why it matters", icon: ShieldCheck },
  { key: "whoMayBeAffected", title: "Who may be affected", icon: Users },
] as const;

export function IntelligenceBriefSkeleton() {
  return (
    <section className="intelligence-brief" aria-label="AI Intelligence Brief" aria-busy="true">
      <div className="brief-heading"><span className="brief-emblem"><Sparkles size={21} aria-hidden="true" /></span><div><p className="eyebrow">RXSIGNAL INTELLIGENCE</p><h2>AI Intelligence Brief</h2></div></div>
      <p role="status" className="brief-loading-label">Preparing your intelligence brief…</p>
      <div className="brief-sections" aria-hidden="true">
        {sections.map(({ key }) => <div className="brief-skeleton-row" key={key}><span className="skeleton-bar skeleton-title" /><span className="skeleton-bar" /><span className="skeleton-bar skeleton-short" /></div>)}
      </div>
    </section>
  );
}

export default function IntelligenceBrief(props: Props) {
  if (props.loading) return <IntelligenceBriefSkeleton />;
  return (
    <section className="intelligence-brief" aria-label="AI Intelligence Brief">
      <div className="brief-heading">
        <span className="brief-emblem"><Sparkles size={21} aria-hidden="true" /></span>
        <div><p className="eyebrow">RXSIGNAL INTELLIGENCE</p><h2>AI Intelligence Brief</h2></div>
        <span className="brief-ai-label"><Sparkles size={11} aria-hidden="true" /> Mock AI summary</span>
      </div>
      <div className="brief-sections">
        {sections.map(({ key, title, icon: Icon }) => (
          <section className="brief-section" key={key}>
            <span className="brief-section-icon"><Icon size={17} aria-hidden="true" /></span>
            <div><h3>{title}</h3><p>{props.brief[key]}</p></div>
          </section>
        ))}
      </div>
      <div className="brief-disclaimer"><Info size={15} aria-hidden="true" /><p>Mock AI summary using fictional data, not generated by Gemini. Review the official FDA source before making clinical decisions. This demo is not medical guidance.</p></div>
    </section>
  );
}
